### ISSUE TITLE
Neutrino 9 release checklist

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/neutrino#1132]
Neutrino 9 beta is now out (see #1129 for more info/to leave feedback).

Once we're ready to release v9 final, we'll also need to:
- [x] #1229: update the docs on `master`, to:
  - make the "v8 Documentation" link point to https://release-v8.neutrinojs.org/ rather than the existing https://neutrinojs.org/
  - make the "Compare all v9 changes" link use a specific version rather than `master`
- [x] #1230: update our auto-changelog settings to use the new release summary feature (CookPete/auto-changelog#69)
- [x] draft the release summary that will be used as the `v9.0.0` commit message body (and thus inserted in the changelog)
- [x] #1505: Open a PR for the v9.0.0 release [following the new release process](https://master.neutrinojs.org/contributing/development/#releasing-a-new-version)
- [x] Once the PR is reviewed/merged, follow the remaining steps in the docs for publishing the new release.
- [x] update the Netlify deploy settings, so that "production" uses `master` branch (rather than `release/v8`), and that `release/v8` is then set to deploy to https://release-v8.neutrinojs.org/ instead
- [x] #1506: update the docs on `release/v8` to:
  - Update page title to reference version ("Neutrino v8")
  - Display in page banner/heading saying "not latest"
  - Add robots.txt to prevent them from appearing in search results
  - Update the hardcoded full URLs in `package/*/README.md` to reference the new subdomain
- [x] set NPM deprecation messages for each of the removed packages (and probably worth revisiting packages that were removed in the past, seeing if they are all deprecated correctly/update messaging)
- [ ] remove the npm `next` and `beta` tags
- [ ] close the `Neutrino 9` milestone on github

**Comment by edmorley** [comment]
>     * draft NPM deprecation messages for each of the removed packages (and probably worth revisiting packages that were removed in the past, seeing if they are all deprecated correctly/update messaging)

New packages to deprecate:
- `@neutrinojs/babel-minify`
- `@neutrinojs/chunk`
- `@neutrinojs/env`
- `@neutrinojs/fork`
- `@neutrinojs/hot`
- `@neutrinojs/image-minify`
- `@neutrinojs/loader-merge`
- `@neutrinojs/minify`
- `@neutrinojs/stylelint`

Legacy packages for which we should check the existing deprecation message:
- `neutrino-lint-base`
- `neutrino-middleware-banner`
- `neutrino-middleware-chunk`
- `neutrino-middleware-clean`
- `neutrino-middleware-compile-loader`
- `neutrino-middleware-copy`
- `neutrino-middleware-dev-server`
- `neutrino-middleware-env`
- `neutrino-middleware-eslint`
- `neutrino-middleware-font-loader`
- `neutrino-middleware-hot`
- `neutrino-middleware-html-loader`
- `neutrino-middleware-html-template`
- `neutrino-middleware-image-loader`
- `neutrino-middleware-loader-merge`
- `neutrino-middleware-minify`
- `neutrino-middleware-named-modules`
- `neutrino-middleware-pwa`
- `neutrino-middleware-start-server`
- `neutrino-middleware-style-loader`
- `neutrino-preset-airbnb-base`
- `neutrino-preset-base`
- `neutrino-preset-jest`
- `neutrino-preset-karma`
- `neutrino-preset-mocha`
- `neutrino-preset-node`
- `neutrino-preset-react`
- `neutrino-preset-web`

**Comment by edmorley** [comment]
> draft the release summary that will be used as the v9.0.0 commit message body (and thus inserted in the changelog)

Possible wording:

```
v9.0.0

Neutrino 9 is our largest release ever, and includes upgrades to webpack 4,
Babel 7 and ESLint 5, along with significant performance improvements.

The biggest breaking change is the necessity to use external tools *alongside*
Neutrino, i.e. webpack, ESLint, Jest, Karma, and others' native CLIs will be
used in tandem with Neutrino rather than being used internally via their APIs.
This fixes many bugs, gives more control over how these tools are run and means
usage of new features is no longer blocked on Neutrino changes to support them.

Please see the migration guide for how to update:
https://neutrinojs.org/migration-guide/#neutrino-v8-to-v9

If you encounter any bugs, have questions or spot improvements that can be made
to the migration guide/docs - we'd love to hear from you:
https://github.com/neutrinojs/neutrino/issues
```

Thoughts?

**Comment by eliperelman** [comment]
@edmorley all the packages should now be moved over. Also 👍 to the release wording.

**Comment by heliocaruccio** [comment]
use 
import { hot } from 'react-hot-loader/root'
and 
export default hot(App);

**Comment by eliperelman** [comment]
@edmorley I think the time has come to pull the trigger. Thoughts?

**Comment by edmorley** [comment]
Sorry for the delayed reply, I've been away for a few weeks this month.

Yeah I agree we should release soon. Perhaps just #1404 and then call it a day? :-)

**Comment by edmorley** [comment]
Also perhaps #1388?

**Comment by ringods** [comment]
The trigger is not pulled yet. Any news on this?

**Comment by edclement** [comment]
I just looked at this checklist to see if there was anything I could assist with? Doesn't appear so (let me know if there is). Really looking forward to seeing v9 released so we can update eslint. Thanks!

**Comment by edmorley** [comment]
@edclement sorry for the delayed reply; new job and no longer actively working with front-end projects (that have a need for something like Neutrino) taking it's toll.

I think we should just release imminently - once #1484 is merged there's not anything critical left:
https://github.com/neutrinojs/neutrino/milestone/6

I've updated the proposed release summary above to reflect ESLint 6:
https://github.com/neutrinojs/neutrino/issues/1132#issuecomment-442440919

**Comment by edmorley** [comment]
I've set/updated the NPM package deprecation messages as follows...

Packages removed in v9:
```bash
for p in @neutrinojs{babel-minify,chunk,env,fork,hot,image-minify,loader-merge,minify,pwa,stylelint}; do npm deprecate ${p} "This package is deprecated. See: https://neutrinojs.org/migration-guide/#neutrino-v8-to-v9" --otp=NNNNNN; done
```

Packages removed in v8:
```bash
for p in neutrino-middleware-{banner,chunk,clean,compile-loader,copy,dev-server,env,eslint,font-loader,hot,html-loader,html-template,image-loader,loader-merge,minify,pwa,start-server,style-loader} neutrino-preset-{airbnb-base,jest,karma,mocha,node,react,web}; do npm deprecate ${p} "This package is deprecated. See: https://neutrinojs.org/migration-guide/#neutrino-v7-to-v8" --otp=NNNNNN; done
```

Packages removed in v6:
```bash
npm deprecate neutrino-middleware-named-modules "This package is deprecated. See: https://neutrinojs.org/migration-guide/#neutrino-v5-to-v6"
```

Packages removed in v5:
```bash
npm deprecate neutrino-lint-base "This package is deprecated. See: https://neutrinojs.org/migration-guide/#neutrino-v4-to-v5"
```

Packages removed in v3:
```bash
npm deprecate neutrino-preset-base "This package is deprecated. Please update to a newer version of Neutrino: https://neutrinojs.org/"
```

And then old tags have been removed from all packages using `npm dist-tag rm <package> <tag-name>`.

With that, we should be all done here :-)
